---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Add PHP repository for Debian
  block:
    - name: Install prerequisites for PHP repository
      apt:
        name: "{{ monica_additional_packages }}"
        state: present
        update_cache: yes

    - name: Add GPG key for PHP repository
      apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present

    - name: Add PHP repository
      apt_repository:
        repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
        state: present
        filename: php-sury
  when: monica_os_family == 'Debian'

- name: Install required packages
  package:
    name: "{{ monica_packages }}"
    state: present
  when: monica_os_family in ['RedHat', 'Debian']

- name: Create monica user
  user:
    name: "{{ monica_user }}"
    group: "{{ monica_group }}"
    system: yes
    create_home: yes
    home: "{{ monica_home }}"

- name: Create application directory
  file:
    path: "{{ monica_app_dir }}"
    state: directory
    owner: "{{ monica_user }}"
    group: "{{ monica_group }}"
    mode: '0755'

- name: Clone Monica repository
  git:
    repo: "https://github.com/monicahq/monica.git"
    dest: "{{ monica_app_dir }}"
    version: "{{ monica_version }}"
    force: yes

- name: Install Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: '0755'

- name: Run Composer installation
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Install PHP dependencies with Composer
  composer:
    command: install
    working_dir: "{{ monica_app_dir }}"
    optimize_autoloader: yes
    no_dev: yes

- name: Copy environment file
  template:
    src: env.j2
    dest: "{{ monica_app_dir }}/.env"
    owner: "{{ monica_user }}"
    group: "{{ monica_group }}"
    mode: '0644'

- name: Set proper permissions
  file:
    path: "{{ monica_app_dir }}"
    owner: "{{ monica_user }}"
    group: "{{ monica_group }}"
    recurse: yes

- name: Generate application key
  command: php artisan key:generate
  args:
    chdir: "{{ monica_app_dir }}"
  become: yes
  become_user: "{{ monica_user }}"

- name: Configure PHP-FPM pool
  template:
    src: www.conf.j2
    dest: "{{ monica_php_fpm_pool_path }}/monica.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart php-fpm

- name: Configure Nginx
  template:
    src: monica.conf.j2
    dest: "{{ monica_web_config_path }}/monica.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Enable site in Nginx (Debian)
  file:
    src: "{{ monica_web_config_path }}/monica.conf"
    dest: "/etc/nginx/sites-enabled/monica.conf"
    state: link
  when: monica_os_family == 'Debian'
  notify: restart nginx

- name: Enable and start PHP-FPM service
  systemd:
    name: "{{ monica_php_service }}"
    enabled: yes
    state: started
  notify: restart php-fpm

- name: Enable and start Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started
  notify: restart nginx
